# Generated by Django 5.1.4 on 2024-12-16 04:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED'), ('COMPLETED', 'COMPLETED')], default='IN_PROGRESS', max_length=11)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_processed_file', to='content_files.processedcontentfile')),
                ('submitted_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_submitted_file', to='content_files.submittedcontentfile')),
            ],
        ),
    ]
