# Generated by Django 5.1.4 on 2024-12-16 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedContentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='./file_store/uploaded/%Y-%m-%d/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedContentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.FilePathField()),
                ('processed_on', models.DateTimeField(auto_now_add=True)),
                ('submitted_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_files.submittedcontentfile')),
            ],
        ),
    ]
